### PR TITLE
Fix #2815 nodejs 0.11 compatibility is Absolute

### LINKED ISSUE #2815: Object #<Object> has no method 'isAbsolute'
#2797 is not compatible with Node version below `0.11.2` as `path.isAbsolute` was only introduced in  `0.11.2`.

### PR DESCRIPTION
**Pull request by soyuka**
Please always submit pull requests on the development branch.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2815
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

### CODE REVIEW

**Comment by vmarchaud** [comment]
We dropped support for nodejs version under 0.12 so i guess we shouldnt merge this one @Unitech  ?

**Comment by soyuka** [comment]
Fine by me \o/. But If you do dropped the support we need to update [the package.json](https://github.com/Unitech/pm2/blob/master/package.json#L6) `engines`.

**Comment by vmarchaud** [comment]
Lets merge the PR and changes the required engine in the package.json so

**Comment by soyuka** [comment]
@vmarchaud WDYT about the engine, should we set it to LTS? Or maybe` >=4`? I'd personally go with `4` instead of `0.12`

**Comment by vmarchaud** [comment]
@soyuka We discussed to drop the support for 0.12 too when we dropped the 0.10 (beginning january), but @Unitech wanted to keep it for a little longer, maybe now should be a good time ? (drop a the same time both)

**Comment by Unitech** [comment]
It's ok to merge that PR for now.
We will drop support for node < 4 on PM2 v3

**Comment by vmarchaud** [comment]
@Unitech But do we upgrade the engine needed to `>=0.12` in the `package.json` like @soyuka said (that will forbid update with node 0.10) ?

**Comment by Unitech** [comment]
yes let's do this

**Pull request merged**
