### PR TITLE
new command: pm2 gc (triggers garbage collection)

### PR DESCRIPTION
**Pull request by jshkurti**
You can now ```pm2 gc``` to manually trigger garbage collection for the PM2 daemon process.

### CODE REVIEW

**Comment by soyuka** [comment]
Is `global.gc()` available to every node version? We could add a log entry
if it's not available?

I think that you could update the docs too :). Sry, wanted to comment on
the code but I'm on the phone right now :).
Le mar. 14 avr. 2015 à 19:42, Joni Shkurti <notifications@github.com> a
écrit :

**Comment by jshkurti** [comment]
I read about it in a blog post from 2013 and it still works on node 0.12.2 so I guess it's been there for a long time :)

**Comment by soyuka** [comment]
Just noticed the `if` :)
Le mar. 14 avr. 2015 à 20:10, Joni Shkurti <notifications@github.com> a
écrit :

**Comment by jshkurti** [comment]
After reading this http://www.jayway.com/2015/04/13/600k-concurrent-websocket-connections-on-aws-using-node-js/

- Added some more flags to node.js.
- Added some documentation
- Added some tests
- Now gc runs in the pm2 worker every 30seconds

**Comment by jshkurti** [comment]
it only concerns PM2 daemon itself for now.
Not the users' apps :)

**Comment by soyuka** [comment]
Oh my bad!
Le mar. 14 avr. 2015 à 21:09, Joni Shkurti <notifications@github.com> a
écrit :

**Pull request merged**
