### PR TITLE
Fix failing npm audit: mkdirp

### PR DESCRIPTION
**Pull request by DMeechan**
NPM Audit was failing with `mkdirp@0.5.1` so I've upgraded it to `0.5.3`.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4638 
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

### CODE REVIEW

**Comment by DMeechan** [comment]
Tests passed locally with Node 12. Any ideas why it breaks with Node 10?

**Comment by StevenChin** [comment]
Any updates on this?

**Comment by DMeechan** [comment]
@StevenChin While waiting for this to be resolved, I ended up doing:

```bash
npm i git+https://github.com/DMeechan/pm2.git
```

It's not ideal but I hope that helps if you're blocked on this like we were 😄

**Comment by StevenChin** [comment]
Thanks @DMeechan! I just might have to do that unfortunately.

**Comment by Unitech** [comment]
mkdirp upgraded to ^1, in the development branch for now, follow this issue to know when it is released: https://github.com/Unitech/pm2/issues/4638

Or:

```
npm install Unitech/pm2#development -g
```

**Pull request closed without merging**
