### PR TITLE
Rename files to allow the repository to be cloned on Windows.

### LINKED ISSUE #1462: Invalid source file names under windows
PM2 source code has some files with names which are invalid in Windows. In particular, ":" is not a valid character. When cloning the repository those files can't be created and are marked as removed.
Ex: all files in "PM2/test/interface/fixtures/"

### PR DESCRIPTION
**Pull request by panuhorsmalahti**
Fixes #1462

### CODE REVIEW

**Comment by panuhorsmalahti** [comment]
Not sure why the builds fail, doesn't seem like the fails are caused by the PR..

Should I create a new PR on the development branch?

**Comment by jshkurti** [comment]
https://travis-ci.org/Unitech/PM2/builds/72974940

Test don't pass. Can't figure out why

**Comment by jshkurti** [comment]
Yes. Make a PR on the development branch please. Always make PR on #development. Always ! :p

**Comment by Unitech** [comment]
thanks, merged in dev (will see what's happening about test failing)

**Pull request closed without merging**
