### PR TITLE
Improve opts.watch

### PR DESCRIPTION
**Pull request by pi0**
This PR Simply checks if watch option is string form of "true", this typo may happen when developers are using `echosystem.json` file and may something like this: `"watch":"true"`  

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Comment by soyuka** [comment]
I do not agree with this as 

```
{
    "watch": true
}
```

Is valid json you should use a boolean, not a string.

**Comment by pi0** [comment]
@soyuka Thats true, but consider also 
```js
{
      "watch": "true"
}
```
Is a valid json! However The only as mentioned in [PM2 docs](http://pm2.keymetrics.io/docs/usage/application-declaration/#advanced-features) only this values are supported for `watch` option: *boolean or []*
Behaviour about string values is not even described. (watching "./true" dir is not strange??)

Anyway feel free to close this PR if is unrelated ;)

**Comment by soyuka** [comment]
It's valid but it's not a boolean. Indeed, a string is specifying a directory to watch and we will not be able to change the behaviour for "true" (because then we would have to do it for "false"). Also, there are other boolean flags, which would not respect this behaviour, which leads to lack of consistency. 

Please use `true` as a boolean if you don't mind ;).

About the PR I'm waiting for other contributors comments on this.

**Comment by vmarchaud** [comment]
People might considering `"true"` as a valid json boolean so i'm okay to merge it (after handling `false` too), indeed we loose consistency but we gain simplicity for end-user.

**Comment by pi0** [comment]
@vmarchaud @soyuka I've changed the casting method:
```js
   if (!app.watch && opts.watch)
      app.watch = JSON.parse(opts.watch);
```
doing `JSON.parse` against on opts.watch, will ensure 3 conditions:
- primitive `true`/`false` => `boolean`
- `"true"`/`"false"` => `boolean`
- other strings => unaccepted (as docs mention only boolean OR arrays allowed)
- [path array] => `array`

Anyway tests are failing as some of them using undocumented form of watch opt (string literal) ! I think it might be better to do following:

1- Mention string support in docs
2- During initialization check for "true"/"false" strings and warn user that she might be doing something wrong. much user friendly and consistency...

**Pull request closed without merging**
