### PR TITLE
Proxy Support

### PR DESCRIPTION
**Pull request by kauegimenes**
Hello, 

I included proxy support for PM2 using `global-tunnel`.
It works with the env variable `http_proxy`

I tested with the command `pm2 interact` and worked fine!

Cheers,

### CODE REVIEW

**Comment by Unitech** [comment]
Damn this is awesome

**Comment by kauegimenes** [comment]
@Unitech Yeah! cheers to global-tunnel =)

**Comment by jshkurti** [comment]
@kauegimenes you're a genius :D

**Comment by Unitech** [comment]
But do you manage to see the keymetrics dashboard with global-tunnel? Because it overiddes the http.request method but data sent from pm2 to keymetrics is raw tcp. Would be curious to know if raw tcp forwarding is well handled by corporate firewalls

**Comment by kauegimenes** [comment]
@Unitech Oh, in that case we should use https://www.npmjs.com/package/tcp-proxy

**Comment by kauegimenes** [comment]
Hey, any update about this?

**Comment by jshkurti** [comment]
As said earlier, PM2 uses raw tcp to communicate with Keymetrics.
Therefore, it doesn't work :/
The tcp-proxy package creates a tcp proxy. It doesn't make your tcp requests use one.

**Comment by kauegimenes** [comment]
@jshkurti Its possible to use `https://github.com/johncant/node-http-tunnel` to tunnel tcp connections through http. 

This could work?

**Comment by lirantal** [comment]
@kauegimenes how about you update this PR and test if it works...?

**Comment by Unitech** [comment]
Closing as we are planing to rewrite the communication between km and pm2

**Pull request closed without merging**
