### PR TITLE
Sort logs by modified time asc.

### PR DESCRIPTION
**Pull request by Tjatse**
#1109

### CODE REVIEW

**Comment by Tjatse** [comment]
Any ideas?

**Comment by jshkurti** [comment]
I don't think this is really important. In any case, showing the last 20 lines of error logs and then the last 20 lines of output logs (or the other way around) is still confusing for the user.
I've been myself confused many times.
That, or the fact that sometimes it shows logs from completely different apps just because they had the same name as my actual app.

The solution to the logs order issue would be to always merge logs and then show the merged logs file.

I think logs should be merged by default and seperated in two different files only if the user specifies it.

**Comment by Tjatse** [comment]
It's not that complicated.
For example, the `stderr` logs were recorded 2 minutes ago, and the `stdout` logs are being recorded every seconds, but when you running `pm2 logs`, the outputs are:
```
[xxx.xx] stdout 1....
[xxx.xx] stdout 2....
[xxx.xx] stdout 3....
[xxx.xx] Error stack:
    from xxx.js line xx....
    function xxx() throw error...
    ....
```

The `stderr` always at the end of logs, that's unreasonable.

**Comment by jshkurti** [comment]
Hey @Tjatse 
I'm completely refactoring `pm2 logs`.
The purpose of this refactor is to get rid of the spawn('tail') and only use natives modules like `fs` to tail logs from files and then use the `bus` event emitter to grab real-time logs.

This way, when you launch a new app while `pm2 logs` is running, you don't have to Ctrl^C and `pm2 logs` again. It just catches the new logs.

And I'm also implementing the sorted by modified time feature.

Here, take a look if you got time : https://github.com/Unitech/PM2/pull/1341

**Comment by Tjatse** [comment]
gocha! it seems great, nice job.

**Pull request closed without merging**
