### PR TITLE
Fix creating pm2 files in correct user $HOME folder

### PR DESCRIPTION
**Pull request by pszypowicz**
https://github.com/Unitech/pm2/issues/1720

### CODE REVIEW

**Comment by Unitech** [comment]
what does the -l option?

**Comment by Unitech** [comment]
https://github.com/Unitech/pm2/commit/419b748e58dc7874d6c5f25723032aa584c7c9ad

**Comment by pszypowicz** [comment]
After the man pages:

```
       -, -l, --login
              Start the shell as a login shell with an environment similar
              to a real login:

                 o      clears all the environment variables except TERM

                 o      initializes the environment variables HOME, SHELL,
                        USER, LOGNAME, and PATH

                 o      changes to the target user's home directory

                 o      sets argv[0] of the shell to '-' in order to make
                        the shell a login shell
```
which here will simply change home directory to user we selected in '-u' option. I think that allowing it to be ANY home directory for pm2 dump won't work as expected.

**Comment by soyuka** [comment]
closing in favor of #1902

**Pull request closed without merging**
