### PR TITLE
set index.html as default entry of dir, issue #2941

### PR DESCRIPTION
**Pull request by JackLLLLL**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2941
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

### CODE REVIEW

**Comment by Unitech** [comment]
fixed via https://github.com/Unitech/pm2/pull/4220
thanks for your contribution

**Comment by linxux** [comment]
@Unitech 
Hi, any plan merge this fixing into master or releases?

**Comment by DaniGuardiola** [comment]
Hi, has this been merged? Thank you :)

**Comment by rwam** [comment]
Hi @Unitech,

https://github.com/Unitech/pm2/pull/4220 doesn't solve this issue because it doesn't work on subdirectories well.

I want to serve a static documentation based on VuePress. Serving the application works fine on the homepage, because it works like a SPA. But reloading a page on a subdirectory only work with adding **/index.html**. A **http://my.tld/sub/index.html** works but **http://my.tld/sub/** results in a `Sorry, check with the site admin for error: EISDIR ..`

I suggest an option like an index setting for directories like DirectoryIndex (Apache) or index (nginx). Otherwise the changes from this PR should be considered.

Thanks & bye
Ralf

**Pull request closed without merging**
