### PR TITLE
CLI Dashboard logs

### PR DESCRIPTION
**Pull request by FDT2k**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #4257 #4245
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

Fixed the CLI Dashboard related to above tickets and from  this comment https://github.com/Unitech/pm2/commit/1186a36e0d652897f694a7c7a1cf697eb3f8a960#r33335634

### CODE REVIEW

**Comment by Unitech** [comment]
thanks, merged via https://github.com/Unitech/pm2/commit/4bb89dc525e89f0d81b8933d8d854150bd950cf5

**Comment by joshhopkins** [comment]
Great to see this fixed. Any idea when this will be released?

**Comment by Ningaro** [comment]
I look forward to the release!

**Comment by fullofcaffeine** [comment]
Is this fix present in v. `4.2.1`? I'm having the same issue.

**Comment by locohost** [comment]
I'm seeing this too. pm2 monit shows my process (just 1 is running) in top left pane, but right logs pane is blank. Is there a fix or workaround?

**Comment by jlsjonas** [comment]
I'm still encountering this, on 4.5.0 meanwhile; consistently can't get logs via `pm2 monit` no matter what I try; `pm2 logs` & `pm2 logs #` works just fine... :thinking:

**Comment by stoplion** [comment]
No logs are showing up for Mac users

**Pull request closed without merging**
