### PR TITLE
- Initial es6 modules support

### PR DESCRIPTION
**Pull request by vpotseluyko**
Please always submit pull requests on the development branch.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

From node v8.8.1 we received unstable es6 modules support with flag --experimental-modules.
(more about it here: https://nodejs.org/api/esm.html)

Es6 modules has broken code which depends on commonJS module system. This pull request allows initially with some hacks support es6 modules.

Note: this provides full backward compatibility with CommonJS projects.
Note: I'd hope this will be included in next pm2 release - while es6 modules are still experimental feature they are worse supporting right now.
I was not really sure where and how shall I pull request it. Hope dev branch was the right choice.
I created simple project for demonstrating es6 modules usage: https://github.com/vpotseluyko/test-es6-pm2

### CODE REVIEW

**Comment by vpotseluyko** [comment]
Note: while pm2 has pmx in it's dependencies this pull request depends on https://github.com/keymetrics/pmx/pull/101

**Comment by Unitech** [comment]
same 👍

**Comment by Unitech** [comment]
@vpotseluyko I've added some tests, it works 

Have you any idea on how it will be possible to monkey patch js modules with this new `import` syntax? We did that on pmx: https://github.com/keymetrics/pmx/blob/master/lib/utils/proxy.js#L7

**Comment by vpotseluyko** [comment]
@Unitech I can look into it only in few days. While mjs work asynchronously by nature, I'm sure that it's a good idea trying monkey path them. So, it's not a new syntax, it's new engine and architecture. Will look closer on it in few days

**Comment by vpotseluyko** [comment]
@Unitech certainly no ideas here

**Pull request merged**
