### PR TITLE
fix package command for BSD tar

### PR DESCRIPTION
**Pull request by poppinlp**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #3951
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

### CODE REVIEW

**Comment by poppinlp** [comment]
I checkout this branch from master branch and send PR to development branch. Seems that makes those other commits there. Dose this matter?

**Comment by Unitech** [comment]
Thanks for this contribution, I will try it out on a mac and eill merge this PR. No it does not matter that some other commits got introduced in it, that’s my fault not having merged the hot fix in dev)

**Comment by poppinlp** [comment]
OK. Thanks.
Actually there's an error in test case code when i run `npm test` on my mac:
image

**Comment by poppinlp** [comment]
Sorry i just find out the [commit message rules](https://github.com/Unitech/pm2/blob/master/CONTRIBUTING.md#commit-message). And the commit in this PR dose not follow that. T_T
Maybe we could check the commit message by git hook? If you'd like, i'll send a PR for that by using [huksy](https://github.com/typicode/husky) and [commitlint](https://github.com/marionebl/commitlint).

**Comment by devinivy** [comment]
I'm interested in this patch well—let me know if I can be of any use! @poppinlp were you able to fix the test issue on OSX?  I imagine that the commit messages may be able to be fixed by squashing the commits when this PR is merged.

**Comment by poppinlp** [comment]
@devinivy OK. I will try to fix the test issue recently if i have time (busy work T_T).

**Pull request closed without merging**
