### PR TITLE
fix #2617 only load startup file with launchctl

### LINKED ISSUE #2617: pm2 can't startup in osx
I want to run pm2 when osx startup, so I follow this [doc](http://pm2.keymetrics.io/docs/usage/startup/).

#### Steps to reproduce
```
pm2 startup
PM2] Init System found: launchd
[PM2] You have to run this command as root. Execute the following command:
sudo env PATH=$PATH:/Users/google/.tnvm/versions/alinode/v2.0.5/bin /Users/google/.tnvm/versions/alinode/v2.0.5/lib/node_modules/pm2/bin/pm2 startup launchd -u google --hp /Users/google
```
then I run the command, but error occurs, here is log:
```
PM2] Init System found: launchd
Platform launchd
Template
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
	  <key>Label</key>
	  <string>com.PM2</string>
	  <key>UserName</key>
	  <string>google</string>
    <key>KeepAlive</key>
    <true/>
	  <key>ProgramArguments</key>
	  <array>
		  <string>/bin/sh</string>
		  <string>-c</string>
		  <string>/Users/google/.tnvm/versions/alinode/v2.0.5/lib/node_modules/pm2/bin/pm2 resurrect</string>
	  </array>
	  <key>RunAtLoad</key>
	  <true/>
	  <key>OnDemand</key>
	  <false/>
	  <key>LaunchOnlyOnce</key>
	  <true/>
	  <key>EnvironmentVariables</key>
    <dict>
      <key>PATH</key>
      <string>/Users/google/.tnvm/versions/alinode/v2.0.5/bin</string>
      <key>PM2_HOME</key>
      <string>/Users/google/.pm2</string>
    </dict>
	  <key>StandardErrorPath</key>
	  <string>/tmp/com.PM2.err</string>
	  <key>StandardOutPath</key>
	  <string>/tmp/com.PM2.out</string>
  </dict>
</plist>

Target path
/Users/google/Library/LaunchAgents/PM2.plist
Command list
[ 'chmod +x /Users/google/Library/LaunchAgents/PM2.plist',
  'launchctl load /Users/google/Library/LaunchAgents/PM2.plist',
  'launchctl start /Users/google/Library/LaunchAgents/PM2.plist',
  'launchctl list' ]
[PM2] Writing init configuration in /Users/google/Library/LaunchAgents/PM2.plist
[PM2] Making script booting at startup...
>>> Executing chmod +x /Users/google/Library/LaunchAgents/PM2.plist
[DONE] 
>>> Executing launchctl load /Users/google/Library/LaunchAgents/PM2.plist
[DONE] 
>>> Executing launchctl start /Users/google/Library/LaunchAgents/PM2.plist
[ERROR] Exit code : 3
[PM2][ERROR] launchctl start /Users/google/Library/LaunchAgents/PM2.plist failed, see error above.
```

#### Software versions used

```
OS         :10.11.6
node.js    :v6.9.2
PM2        :2.2.3
```

### PR DESCRIPTION
**Pull request by soyuka**
Please always submit pull requests on the development branch.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #2617
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

**Comment by vmarchaud** [comment]
Don't have mac to test it, maybe @Unitech can ?

**Comment by Unitech** [comment]
Nice! Yes I will try this by tomorrow - I guess it works well as soyuka has
a mac too :)

**Comment by soyuka** [comment]
Tested on sierra, took some time! On hackintosh I need to upgrade and it's a pain \o/

**Comment by soyuka** [comment]
I removed the list, because launchctl will not list processes it doesn't manage and pm2 has it's own daemon.

**Pull request merged**
