### PR TITLE
Add child process count to pm2 list

### PR DESCRIPTION
**Pull request by soyuka**
Please always submit pull requests on the development branch.

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1869 (a good start to fix this issue)
| License       | MIT
| Doc PR        | na

@vmarchaud lmk if you can add appveyor to our ci stack for pull requests.

### CODE REVIEW

**Comment by Unitech** [comment]
works great, lgtm, @vmarchaud thoughts?

**Comment by vmarchaud** [comment]
We can definitely merge this and see how its behaving with our different configuration :)

**Comment by soyuka** [comment]
@Unitech can you add appveyor to github?

**Comment by soyuka** [comment]
I forgot I had that and forced push, I must have a copy at home though :cat:

**Pull request closed without merging**
