### PR TITLE
Added autostart parameter to optionally prevent immediately starting

### PR DESCRIPTION
**Pull request by ultimate-tester**
…applications

(cherry picked from commit b34498f45e6138a6e7f31c6a7f0ddfed768eee76)

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #5711, #2504, #5776, #5768, #1956, #1041, #3759, #5648, #5479
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pulls

### CODE REVIEW

**Comment by ultimate-tester** [comment]
This PR seems to work better, it looks like all license agreements are now in place/signed. Hoping it will be accepted soon!

**Comment by mudmixer-wes** [comment]
@Unitech any chance this PR could get some love? This feels like such a value-add to an already awesome library.

**Comment by mudmixer-wes** [comment]
@Unitech bumping this PR. @ultimate-tester fixed 6-7 tickets with this one PR. How can we help get this across the finish line?

**Comment by alexgalkin** [comment]
@Unitech please check this. Pretty important update.

**Comment by mudmixer-wes** [comment]
Yay!!!

**Comment by KeKs0r** [comment]
@Unitech is it possible to make a release with this change included?

**Pull request merged**
