### PR TITLE
Fix shell scripts EOL on Windows

### PR DESCRIPTION
**Pull request by bisubus**
Please always submit pull requests on the development branch.

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

*Please update this template with something that matches your PR*

### CODE REVIEW

**Comment by Unitech** [comment]
could you make this PR on development branch? thx

**Comment by bisubus** [comment]
@Unitech Sure.

**Comment by soyuka** [comment]
Need rebasing.

**Comment by bisubus** [comment]
@soyuka I see. Did it.

**Comment by soyuka** [comment]
:+1: thanks! LGTM @Unitech

**Comment by Unitech** [comment]
thansk, merged

**Pull request merged**
