### PR TITLE
feat: stop-exit-codes

### PR DESCRIPTION
**Pull request by Lazyuki**
| Q             | A
| ------------- | ---
| Bug fix?      | yes (adding a missing feature mentioned in the docs)
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #5208
| License       | MIT
| Doc PR        | https://github.com/pm2-hive/pm2-hive.github.io/pull/218 (already added)

This feature `stop-exit-codes` was first introduced by @jack1142 in the PR #5048 along with the documentation change PR https://github.com/pm2-hive/pm2-hive.github.io/pull/218. However for some reason, only the documentation PR was merged without the actual code and now the [live documentation website lists a feature that doesn't actually exist](https://pm2.keymetrics.io/docs/usage/restart-strategies/#skip-auto-restart-for-specific-exit-codes). This of course resulted in this issue #5208 being created.

This PR is continued from jack's PR and adds a few tests. Someone else already made an attempt in #5241 but seems like it was closed without any reason.

### CODE REVIEW

**Comment by jrtg** [comment]
Would love to see this merged please, will help us out a lot 👍

**Comment by dperolio** [comment]
Yes please.

**Comment by internpoon** [comment]
Can this be merged please ?

**Comment by negreanucalin** [comment]
This feature should be merged, could somebody provide feedback so that it can move forward?

**Comment by TotalLag** [comment]
@Unitech any guidance here?

**Comment by bramvbilsen** [comment]
This is already mentioned in the [docs](https://pm2.keymetrics.io/docs/usage/restart-strategies/), but the feature itself does not seem to exist yet.
I think this should be removed from the docs until this gets merged.

**Comment by smashah** [comment]
In docs, passes tests but not merged?

Considering the fast-pace of Node ecosystem in general, I think this project can do with a bias towards shipping and letting the community deal with potential regressions (that too solved with a bias towards shipping).

Please merge this so the featureset is in-line with current documentation, please. It has been 7 months already.

Thanks

**Comment by dreadkopp** [comment]
feature is mentioned in docs since 2021, this pull request / patch / bugfix is nearly a year old...

really like to see this feature (or at least removed from docs...)

I am quite confused about this. considered switchich from supervisor to pm2 but things like leave me wondering how solid this project is

**Comment by smashah** [comment]
@Unitech can we bump this PR and get it merged please?

**Comment by risserlabs-com** [comment]
Merge this please

**Comment by smashah** [comment]
When is this going to be released?

**Comment by luketych** [comment]
Please ass support for stop-exit-codes option in the pm2 ecosystem file. Currently it only works in the CLI options.

**Comment by gamersindo1223** [comment]
this feature is currently in development:
to install it just use
```npm install -g github:Unitech/pm2#development```

@smashah

**Pull request merged**
