### PR TITLE
Darwin startup script

### PR DESCRIPTION
**Pull request by Tjatse**
Base on [launchd(8)](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/launchd.8.html)

Tested on 
- OS X 10.8.5
- OS X 10.9.4

Need more tests.

### CODE REVIEW

**Comment by soyuka** [comment]
#791

Looks nice!

**Comment by Tjatse** [comment]
@soyuka I remember that you are having the Darwin environment, can you pull the [repo](https://github.com/Tjatse/PM2/tree/darwin-startup-script) and make a simple test? hah

```bash
localhost:PM2-Tjatse $ bin/pm2 kill
localhost:PM2-Tjatse $ bin/pm2 start test/fixtures/server.js
localhost:PM2-Tjatse $ bin/pm2 start test/fixtures/signal.js
localhost:PM2-Tjatse $ sudo bin/pm2 startup -u soyuka
# reboot
```

**Comment by soyuka** [comment]
I'm not @ home right now, I'd be able to test tonight and let you now :).

**Comment by Tjatse** [comment]
@soyuka :+1:

**Comment by soyuka** [comment]
Had to `npm link`* but it's working perfectly fine :).

*`pm2 dump` => `pm2 command not found` with an error message about the startup choice.

**Comment by Tjatse** [comment]
@soyuka Just forgot to mention that in the test script. :p

**Comment by soyuka** [comment]
np, it's just that the https://github.com/Tjatse/PM2/blob/618e2da660e64d171b5d021dc40c434b96e88aa4/lib/CLI.js#L426 error message does not reflect the same error ^^. Nevermind, this will not happend with a global installed pm2 :).

I think you can merge this + close #791, thanks!

**Comment by Tjatse** [comment]
@soyuka Yup, Gotcha, you're running this on a pure env - removed official PM2, but I'm not. Haha.
If @Unitech has no objection, I am going to merge this.

Again, appreciate your help.

**Pull request merged**
